package com.coxandkings.utils;
   
import java.io.ByteArrayInputStream;
import java.io.IOException;

import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.rtf.RTFEditorKit;
import javax.xml.bind.DatatypeConverter;

public class RTFConverter {
   public static String decodeBase64WithRTF(String str) throws IOException, BadLocationException {
		// TODO Auto-generated method stub
		//String str="e1xydGYxXGZiaWRpc1xhbnNpXGFuc2ljcGcxMjUyXGRlZmYwXGRlZmxhbmcxNjM5M3tcZm9udHRibHtcZjBcZnN3aXNzXGZwcnEyXGZjaGFyc2V0MCBNaWNyb3NvZnQgU2FucyBTZXJpZjt9e1xmMVxmbmlsXGZjaGFyc2V0MCBNaWNyb3NvZnQgU2FucyBTZXJpZjt9fQ0KXHZpZXdraW5kNFx1YzFccGFyZFxsdHJwYXJcZjBcZnMxNyBUaGVzZSBhcmUgSW5zdGFudCBQdXJjaGFzZSBPbmUgV2F5IFJldGFpbCBCdXNpbmVzcyBGYXJlcyBhcHBsaWNhYmxlIGZvciBGSVQgYm9va2luZ3Mgb25seS4gTWluaW11bSAxIFBhc3NlbmdlcnMgYW5kIE1heGltdW0gOCBQYXNzZW5nZXJzIGFyZSBwZXJtaXR0ZWQgdG8gYm9vayBhdCBnaXZlbiBwb2ludCBvZiB0aW1lLiBGYXJlcyBjYW4gYmUgY29tYmluZWQgd2l0aCBhbnkgb3RoZXIgZmFyZSB0eXBlIGFuZCBwcm9kdWN0IG9uIEdvYWlyIG5ldHdvcmsuIFxwYXINClxwYXINClxiIE5vIC0gU2hvdyBQZW5hbHR5XGIwICA6IDEwMCVccGFyDQpccGFyDQpcYiBDYW5jZWxsYXRpb24gUGVuYWx0aWVzXGIwIDogMTAwJSBjYW5jZWxsYXRpb24gY2hhcmdlcyB3aXRoaW4gMiBob3VycyBvZiB0aGUgZmxpZ2h0IGRlcGFydHVyZSB0aW1lLiBJTlIgMjIyNS8tIGNhbmNlbGxhdGlvbiBjaGFyZ2VzIHBlciBzZWN0b3IgcGVyIHBhc3NlbmdlciBmb3IgdGhlIGJvb2tpbmdzIGNhbmNlbGxlZCAyIGhvdXJzIG91dHNpZGUgdGhlIGRlcGFydHVyZSBvZiB0aGUgZmxpZ2h0LlxwYXINClxwYXINClxiIENoYW5nZSBGZWVzXGIwIDogTmlsIENoYXJnZXNccGFyDQpccGFyDQpHb0FpciByZXNlcnZlcyB0aGUgcmlnaHQgdG8gY2hhbmdlIHRoZSBDYW5jZWxsYXRpb24vQ2hhbmdlIEZlZXMgZnJvbSB0aW1lIHRvIHRpbWUgd2l0aG91dCBhbnkgcHJpb3IgaW50aW1hdGlvbi5ccGFyDQpccGFyZFxsdHJwYXJcZjFcZnMxN1xwYXINCn0NCg==";
	  // String str1="e1xydGYxXGZiaWRpc1xhbnNpXGFuc2ljcGcxMjUyXGRlZmYwXGRlZmxhbmcxNjM5M3tcZm9udHRibHtcZjBcZnN3aXNzXGZwcnEyXGZjaGFyc2V0MCBNaWNyb3NvZnQgU2FucyBTZXJpZjt9e1xmMVxmbmlsXGZjaGFyc2V0MCBNaWNyb3NvZnQgU2FucyBTZXJpZjt9fQ0KXHZpZXdraW5kNFx1YzFccGFyZFxsdHJwYXJcZjBcZnMxNyBUaGVzZSBhcmUgSW5zdGFudCBQdXJjaGFzZSBPbmUgV2F5IFJldGFpbCBCdXNpbmVzcyBGYXJlcyBhcHBsaWNhYmxlIGZvciBGSVQgYm9va2luZ3Mgb25seS4gTWluaW11bSAxIFBhc3NlbmdlcnMgYW5kIE1heGltdW0gOCBQYXNzZW5nZXJzIGFyZSBwZXJtaXR0ZWQgdG8gYm9vayBhdCBnaXZlbiBwb2ludCBvZiB0aW1lLiBGYXJlcyBjYW4gYmUgY29tYmluZWQgd2l0aCBhbnkgb3RoZXIgZmFyZSB0eXBlIGFuZCBwcm9kdWN0IG9uIEdvYWlyIG5ldHdvcmsuIFxwYXINClxwYXINClxiIE5vIC0gU2hvdyBQZW5hbHR5XGIwICA6IDEwMCVccGFyDQpccGFyDQpcYiBDYW5jZWxsYXRpb24gUGVuYWx0aWVzXGIwIDogMTAwJSBjYW5jZWxsYXRpb24gY2hhcmdlcyB3aXRoaW4gMiBob3VycyBvZiB0aGUgZmxpZ2h0IGRlcGFydHVyZSB0aW1lLiBJTlIgMjIyNS8tIGNhbmNlbGxhdGlvbiBjaGFyZ2VzIHBlciBzZWN0b3IgcGVyIHBhc3NlbmdlciBmb3IgdGhlIGJvb2tpbmdzIGNhbmNlbGxlZCAyIGhvdXJzIG91dHNpZGUgdGhlIGRlcGFydHVyZSBvZiB0aGUgZmxpZ2h0LlxwYXINClxwYXINClxiIENoYW5nZSBGZWVzXGIwIDogTmlsIENoYXJnZXNccGFyDQpccGFyDQpHb0FpciByZXNlcnZlcyB0aGUgcmlnaHQgdG8gY2hhbmdlIHRoZSBDYW5jZWxsYXRpb24vQ2hhbmdlIEZlZXMgZnJvbSB0aW1lIHRvIHRpbWUgd2l0aG91dCBhbnkgcHJpb3IgaW50aW1hdGlvbi5ccGFyDQpccGFyZFxsdHJwYXJcZjFcZnMxN1xwYXINCn0NCg==";
		String decoded = new String(DatatypeConverter.parseBase64Binary(str));
		System.out.println("After decoded : "+decoded);
		byte[] rtfBytes= decoded.getBytes();
		RTFEditorKit rtfParser = new RTFEditorKit();
		Document document = rtfParser.createDefaultDocument();
		rtfParser.read(new ByteArrayInputStream(rtfBytes), document, 0);
		String text = document.getText(0, document.getLength());
		System.out.println("After converstion : "+text);
		return text;

	}
}
